//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.CpGlinfo = new HashSet<CpGlinfo>();
            this.CustomerAddress = new HashSet<CustomerAddress>();
        }
    
        public int ID { get; set; }
        public string KhID { get; set; }
        public string KhName { get; set; }
        public string beizhu { get; set; }
        public string chuanzhen { get; set; }
        public string youxiang { get; set; }
        public string Hone { get; set; }
        public string Time { get; set; }
        public Nullable<bool> State { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CpGlinfo> CpGlinfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerAddress> CustomerAddress { get; set; }
    }
}
