//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CpGlinfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CpGlinfo()
        {
            this.BreakageDetailed = new HashSet<BreakageDetailed>();
            this.CycleCountDetailed = new HashSet<CycleCountDetailed>();
            this.MovementDetailed = new HashSet<MovementDetailed>();
            this.ReturnsDetailed = new HashSet<ReturnsDetailed>();
            this.StockRemovalDetailed = new HashSet<StockRemovalDetailed>();
            this.StorageDetailed = new HashSet<StorageDetailed>();
        }
    
        public int CpID { get; set; }
        public string Cpbh { get; set; }
        public string CpXsName { get; set; }
        public Nullable<int> CpSx { get; set; }
        public Nullable<int> CpXx { get; set; }
        public Nullable<int> CpPrice { get; set; }
        public string Specification { get; set; }
        public Nullable<int> CpLb { get; set; }
        public Nullable<int> CpJlName { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CkId { get; set; }
        public Nullable<int> KwId { get; set; }
        public string remark { get; set; }
        public Nullable<bool> State { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BreakageDetailed> BreakageDetailed { get; set; }
        public virtual Cangku Cangku { get; set; }
        public virtual Client Client { get; set; }
        public virtual CpLbinfo CpLbinfo { get; set; }
        public virtual JLinfo JLinfo { get; set; }
        public virtual LocationManagement LocationManagement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CycleCountDetailed> CycleCountDetailed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovementDetailed> MovementDetailed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnsDetailed> ReturnsDetailed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockRemovalDetailed> StockRemovalDetailed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageDetailed> StorageDetailed { get; set; }
    }
}
