//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationManagement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocationManagement()
        {
            this.BreakageDetailed = new HashSet<BreakageDetailed>();
            this.CpGlinfo = new HashSet<CpGlinfo>();
            this.MovementDetailed = new HashSet<MovementDetailed>();
            this.MovementDetailed1 = new HashSet<MovementDetailed>();
            this.ReturnsDetailed = new HashSet<ReturnsDetailed>();
            this.StockRemovalDetailed = new HashSet<StockRemovalDetailed>();
            this.StorageDetailed = new HashSet<StorageDetailed>();
        }
    
        public int kwID { get; set; }
        public string kwName { get; set; }
        public Nullable<int> CangKu { get; set; }
        public Nullable<int> kwType { get; set; }
        public Nullable<int> Zhuangtai { get; set; }
        public Nullable<int> Isdefault { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<bool> Shuju { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BreakageDetailed> BreakageDetailed { get; set; }
        public virtual Cangku Cangku1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CpGlinfo> CpGlinfo { get; set; }
        public virtual LocationManagementType LocationManagementType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovementDetailed> MovementDetailed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovementDetailed> MovementDetailed1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnsDetailed> ReturnsDetailed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockRemovalDetailed> StockRemovalDetailed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageDetailed> StorageDetailed { get; set; }
    }
}
