//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StorageEntities : DbContext
    {
        public StorageEntities()
            : base("name=StorageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Authority> Authority { get; set; }
        public virtual DbSet<Breakage> Breakage { get; set; }
        public virtual DbSet<BreakageDetailed> BreakageDetailed { get; set; }
        public virtual DbSet<Cangku> Cangku { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<CpGlinfo> CpGlinfo { get; set; }
        public virtual DbSet<CpLbinfo> CpLbinfo { get; set; }
        public virtual DbSet<CustomerAddress> CustomerAddress { get; set; }
        public virtual DbSet<CycleCount> CycleCount { get; set; }
        public virtual DbSet<CycleCountDetailed> CycleCountDetailed { get; set; }
        public virtual DbSet<Function> Function { get; set; }
        public virtual DbSet<JLinfo> JLinfo { get; set; }
        public virtual DbSet<LocationManagement> LocationManagement { get; set; }
        public virtual DbSet<LocationManagementType> LocationManagementType { get; set; }
        public virtual DbSet<Movement> Movement { get; set; }
        public virtual DbSet<MovementDetailed> MovementDetailed { get; set; }
        public virtual DbSet<Returns> Returns { get; set; }
        public virtual DbSet<ReturnsDetailed> ReturnsDetailed { get; set; }
        public virtual DbSet<StockRemoval> StockRemoval { get; set; }
        public virtual DbSet<StockRemovalDetailed> StockRemovalDetailed { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
        public virtual DbSet<StorageDetailed> StorageDetailed { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<SysDepart> SysDepart { get; set; }
        public virtual DbSet<SysRole> SysRole { get; set; }
        public virtual DbSet<SysStatus> SysStatus { get; set; }
    }
}
