//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movement()
        {
            this.MovementDetailed = new HashSet<MovementDetailed>();
        }
    
        public string MovementID { get; set; }
        public string MovementType { get; set; }
        public string Associatednumber { get; set; }
        public Nullable<int> MovementCount { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string StateText { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<bool> DataState { get; set; }
    
        public virtual Admin Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovementDetailed> MovementDetailed { get; set; }
    }
}
