//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageDetailed
    {
        public int StoragedetailedID { get; set; }
        public string StorageIDS { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> StorageNumber { get; set; }
        public Nullable<decimal> Summoney { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<decimal> Batch { get; set; }
    
        public virtual CpGlinfo CpGlinfo { get; set; }
        public virtual LocationManagement LocationManagement { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
